version: '3'

networks:
  net:

services:
  postgres:
    image: "postgres:14.6"
    ports:
      - "5432:5432"
      - "10051:10051"
      - "10050:10050"
      - "80:80"
      - "8080:8080"
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
    volumes:
      - ./conf/create.sql:/docker-entrypoint-initdb.d/create.sql
    container_name: postgres
    networks:
      net:
        aliases:
          - postgres

  zabbix-server-pgsql:
    image: "zabbix/zabbix-server-pgsql:6.2.4-ubuntu"
#    ports:
#      - "10051:10051"
    volumes:
      - ./conf/zabbix_server.conf:/etc/zabbix/zabbix_server.conf
    environment:
      DB_SERVER_HOST: "127.0.0.1"
      DB_SERVER_PORT: "5432"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
    container_name: zabbix-server-pgsql
    network_mode: "service:postgres"
    depends_on:
      - postgres
  #    networks:
  #      net:
  #        aliases:
  #          - zabbix-server-pgsql

  zabbix-agent2:
    image: "zabbix/zabbix-agent2:6.2.4-ubuntu"
#    ports:
#      - "10050:10050"
    volumes:
      - ./conf/postgresql.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/postgresql.conf
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "127.0.0.1"
    container_name: zabbix-agent2
    network_mode: "service:postgres"
    depends_on:
      - zabbix-server-pgsql
#    networks:
#      net:
#        aliases:
#          - zabbix-agent2

  zabbix-web-apache-pgsql:
    image: "zabbix/zabbix-web-apache-pgsql:6.2.4-ubuntu"
#    ports:
#      - "80:80"
#      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: "127.0.0.1"
      ZBX_SERVER_PORT: "10051"
      DB_SERVER_HOST: "127.0.0.1"
      DB_SERVER_PORT: "5432"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    container_name: zabbix-web-apache-pgsql
    network_mode: "service:postgres"
    depends_on:
      - zabbix-server-pgsql
#    networks:
#      net:
#        aliases:
#          - zabbix-web-apache-mysql
