version: '3'

networks:
  net:

services:
  postgres:
    image: "radondb/radondb-postgresql:12.12-v1.1.0"
    ports:
      - "5432:5432"
      - "3306:3306"
      - "10051:10051"
      - "10050:10050"
      - "80:80"
      - "8080:8080"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PG_CONFIG_max_connections: 101
    container_name: postgres
    networks:
      net:
        aliases:
          - postgres

  mysql:
    image: "mysql:8.0.30"
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./conf/create.sql:/docker-entrypoint-initdb.d/create.sql
    container_name: mysql
    network_mode: "service:postgres"
#    networks:
#      net:
#        aliases:
#          - mysql

  zabbix-server-mysql:
    image: "zabbix/zabbix-server-mysql:6.2.4-ubuntu"
#    ports:
#      - "10051:10051"
    environment:
      DB_SERVER_HOST: "127.0.0.1"
      DB_SERVER_PORT: "3306"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
    container_name: zabbix-server-mysql
    network_mode: "service:postgres"
    depends_on:
      - mysql
  #    networks:
  #      net:
  #        aliases:
  #          - zabbix-server-mysql

  zabbix-agent2:
    image: "zabbix/zabbix-agent2:6.2.4-ubuntu"
#    ports:
#      - "10050:10050"
    volumes:
      - ./conf/postgresql.conf:/etc/zabbix/zabbix_agent2.d/plugins.d/postgresql.conf
    environment:
      ZBX_SERVER_HOST: "127.0.0.1"
    container_name: zabbix-agent2
    network_mode: "service:postgres"
    depends_on:
      - zabbix-server-mysql
#    networks:
#      net:
#        aliases:
#          - zabbix-agent2

  zabbix-web-apache-mysql:
    image: "zabbix/zabbix-web-apache-mysql:6.2.4-ubuntu"
#    ports:
#      - "80:80"
#      - "8080:8080"
    environment:
      ZBX_SERVER_HOST: "127.0.0.1"
      ZBX_SERVER_PORT: "10051"
      DB_SERVER_HOST: "127.0.0.1"
      DB_SERVER_PORT: "3306"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_DATABASE: "zabbix"
    container_name: zabbix-web-apache-mysql
    network_mode: "service:postgres"
    depends_on:
      - zabbix-server-mysql
#    networks:
#      net:
#        aliases:
#          - zabbix-web-apache-mysql
